### ISSUE TITLE
PaymentRequest critical data

### ISSUE THREAD

**Issue by asma1402** [w3c/browser-payment-api#1003]
Hello, 
I'm using payment request API, and i created a payment method,before i call the show() method, I ask the user to enroll, then i give him a token, this token is a very  critical data for my payment method, i use this token like the card number and cvc to make payments, 
Im asking if there is a way to store this token **securely** - preferably natively - and to be **used each time** the user choose to pay with my payment method.

All tahnks!

@stephenmcgruer 
@rsolomakhin 
@ianbjacobs

**Comment by ianbjacobs** [comment]
Hi @asma1402,

This question extends beyond the scope of the Payment Request API into areas such as client-side storage [1].
I'm going to close this issue (because it's not an issue on the specification). 

(Others are free to continue to comment; I'm just closing the issue.)

Ian

[1] https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Client-side_web_APIs/Client-side_storage

**Comment by cyberphone** [comment]
As a user of payment request you may contact me using the email address listed on GitHub.
https://github.com/cyberphone/saturn/blob/13c16983c9f8c21d1eb1f0f04f38395716f7cae1/keyprovider/src/org/webpki/saturn/keyprovider/KeyProviderInitServlet.java#L326
A few questions:
What kind of payment application are you using?
Are you using a "token" multiple times?  That is generally not a good idea.
Anders
