### ISSUE TITLE
Terms and conditions next to "Pay" button

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#195]
We have received feedback from merchants that some countries may require to show "Accept [Terms and Conditions](https://example.com)" checkbox right next to the "Pay" button. Should we add a `termsAndConditions` field to `PaymentOptions`? This can be either a URL, plain text, or restricted subset of HTML.

Note, this is somewhat related to discussion in issue https://github.com/w3c/browser-payment-api/issues/113.

**Comment by nickjshearer** [comment]
Presumably the API is triggered by some kind of action on the merchant's website...why can the terms not be displayed there? Why should the user agent assume the responsibility for displaying and ensuring a user has accepted a site's arbitrary terms and conditions when the website could do it prior to initiating a payment?

**Comment by rsolomakhin** [comment]
That sounds logical, @nickjshearer. Let's get some merchants to try PaymentRequest with your recommended setup and see whether they find it acceptable.

**Comment by nickjshearer** [comment]
Cool. If it turns out there's an issue we should revisit.

**Comment by adrianhopebailie** [comment]
I think this will actually be handled by the payment app. Payment apps will need to be aware of the specific jurisdictional requirements to process payments online for whatever payment methods they support.

If there is a requirement for the merchant to provide terms and conditions (a URL) so that the payment app can display this link when the user auths the payment then I'd expect that URL to be passed in the payment method's custom data.

As with many of the custom data fields, we may find over time that there is sufficient commonality for us to add a new field in the base request at which time we can do that.

I'd suggest we close this issue and re-look at this when we have some market feedback.

**Comment by nickjshearer** [comment]
I don't necessarily agree with the idea this should be handled by the payment app, but I do agree it's something we can revisit at a later date and this issue could probably be closed off for now.

**Comment by rsolomakhin** [comment]
Closing for now. May revisit later.

**Comment by Crissov** [comment]
Just for the record, dismissing this use case has contributed to some non-adoption, e.g. https://github.com/PAYONE-GmbH/magento-2/issues/379

**Comment by ianbjacobs** [comment]
Thank you for the update, @crissov. 

I note that the goal of Secure Payment Confirmation (SPC) is to capture user consent: (1) Browser-managed UX shows terms and conditions, then (2) displayed terms and conditions are signed with FIDO authenticators and can be validated by relying-parties. 

Right now SPC only handles "this single transaction" terms and conditions, but we have discussed additional use cases such as recurring payments or other related terms and conditions.
