### ISSUE TITLE
Concern on Payment Method Identifier requirement

### ISSUE THREAD

**Issue by maoyanhua** [w3c/browser-payment-api#200]
Sorry for jumping into the discussion late in the game and my apology if the topic has previously been discussed already. Anyways, after reading the requirement on PMI I have the following concerns

> Requirement 2: It must be possible for anyone to mint a PMI for a payment method under their control. 

The reality here is, payment method is rarely fully under one party's control. Just take a Visa debit card issued by citi bank for example. It is a collaboration between, visa, PCI and citi bank. On page, citi bank is card issuer, however, they need to work with PCI and visa to make sure the plastic card and back end are in complaint. To that point, it is unclear if this method should be paymentcard/debit/visa/citi or citi/paymentcard/debit/visa (or any other combination) under the current proposal.

My proposal is that we should consider add a fifth requirement to **make it easy for multiple parties to collaborate and mint payment method together** 

Also, under the current proposal, paymentcard/debit/visa/citi and citi/paymentcard/debit/visa are two different PMI when they should in fact be the same

Another requirement I think we should add is to ensure that **we can easily specify a class of payment method. e.g. all visa debit card, or all visa card accepts USD.** so that the payment app can easily specify the list of payment method if prefers (or accepts)

 I would like to propose a different PMI schema, that uses a collection of properties, e.g.,
{ http://pci.org/paymentcard/debit, http://visa.com/visa/, http://citi.com/citicards, http://w3c.org/payment/currency/usd} 
-  two PMI are equivalent if they have the same set of properties (which in turn can be evaluated using URL equivalency or have short names)
- Since different organization owns their own dominate, they would be easily mint a PMI if they fully owns and there is no collaboration with other organization
- This would also allows multiple organization to collaborate, as each of them would be minting properties that they own. 
- The new schema also allows the payment apps to easily specify it accepts certain class of payment method, e.g. it can say only accepts visa debit card by requiring the following two properties: { http://pci.org/paymentcard/debit, http://visa.com/visa/}

**Comment by ianbjacobs** [comment]
@maoyanhua, 

Thanks for writing. One of the issues you raised (about subclasses) is covered in issue 30:
   https://github.com/w3c/browser-payment-api/issues/30

I've been trying to capture hte use cases here:
 https://github.com/w3c/webpayments/wiki/PMI_Notes

Regarding the point about minting identifiers, the group has recently resolved that payment method identifiers will be absolute URLs. (We've not yet formally decided NOT to have
some form of short name, but if we do I would expect those would normalize to absolute URLs.)
URL "ownership" would be defined outside of our specification.

Regarding your matching algorithm: that's still an open question for us. If we do not adopt any grouping or subclassing semantics in v1, then the matching algorithm will be "simple" (e.g., some form of URL equivalence). It will grow in complexity the more semantics we want to support.

Would you be ok if I closed this issue and we continue "grouping semantics" discussions in issue 30?

Thanks!

Ian

**Comment by adrianhopebailie** [comment]
@ianbjacobs I think this issue is worth keeping open to get clarity discuss the different requirements of **owning** a PMI for the sake of dereferencing vs matching.

By that I mean, for the URL http://example.com we can assume the **owner** of the URL is the owner of the domain example.com but that doesn't mean they also **own** all of the payment method specs that use that URL as a PMI. 

If that sounds wrong, then @maoyanhua 's assertion about industry associations is a great use case to illustrate.

Let's assume that the owner of example.com is a company called Example Corp. Let's assume Example Corp is part of an industry association called The Payment Processors Association and the association has defined a payment method supported by their members and published a payment method spec at http://payproc.org/payment-methods/paynice_spec.html. That payment method spec lists the following PMIs as being related to this payment method:
- http://payproc.org/payment-methods/paynice
- http://example.com/payment-methods/paynice
- http://otherco.com/payment-methods/paynice
- http://3pay.io/payment-methods/paynice

**Ownership** of those URL's is only important if they are going to be dereferenced because the owner of the URL controls what resource sits at http://example.com/payment-methods/paynice.

So if Example Corp wants to host a resource at http://example.com/payment-methods/paynice they can do that. Right now we are not proposing to set any expectations for what that resource might be or if it needs to even exist.

For the purposes of matching the browser (payment mediator) doesn't really care who owns the URL because it doesn't dereference it as part of the matching process. All the mediator cares about is if that URL _matches_ (and I use the term loosely because we are still defining the algorithm) another PMI which would help it determine if a payment app can process a given payment request.

**Comment by maoyanhua** [comment]
@ianbjacobs  I think #30 is slightly different from my concern here. in 30, we talked about subclassing/hierarchy, which to me implies a tree structure. what i think is certain properties, such as card network (visa vs master) and card type (debit vs credit) are orthogonal dimensions

**Comment by ianbjacobs** [comment]
@adrianhopebailie, 

I do not understand from what you wrote why we need to keep the issue open. I agree with the following statements:
- A payment method (note "method" not "method specification" here)  may be identified by more than one PMI.
- A payment method specification may be referenced by entities who do not control that specification. 
- The matching algorithms we have been discussing do not involve dereferencing URLs.

@maoyanhua wrote:

> in 30, we talked about subclassing/hierarchy, which to me implies a tree structure.

I don't believe that #30 assumes a tree. In fact, I've been in discussion with @mattsaxon and @adrianhopebailie about writing up a proposal for using query parameters as a way to represent a graph of information.

Ian (still thinking we can close this issue)

**Comment by adrianhopebailie** [comment]
Addressed in the following proposal: https://github.com/w3c/browser-payment-api/issues/205
