### ISSUE TITLE
Should the amount be in decimal or cents?

### ISSUE THREAD

**Issue by pazguille** [w3c/browser-payment-api#204]
The spec says the amount should be:

> A string containing the decimal monetary value. If a decimal separator is needed then the string must use a single U+002E FULL STOP character as the decimal separator.

I think use amount in cents is better than decimal because different countries officially designate different symbols for the decimal mark. For example, German and Spanish use comma as decimal separator and period for thousands. 

``` js
{
  "currency": "USD",
  "value" : "5500"
}
```

Also, the following Payments API use amount in cents:
- https://stripe.com/docs/api#charges
- https://dev.recurly.com/docs/create-transaction
- https://developers.getmango.com/en/api/charges/#the-object

Thanks!

**Comment by rsolomakhin** [comment]
Thank you for the suggestion.

#### Cents vs Dollars

We are not using cents because we want to be compatible with such standards as [ISO 20022](https://www.iso20022.org/standardsrepository/public/wqt/Description/mx/dico/datatypes/_YX4O9tp-Ed-ak6NoX_4Aeg_-836081793), which allows up to 5 fractional digits. We can express $50.001 as `"value": "50.001"`, but your proposal would result in `"value": "5000.1"`. I think the latter would be confusing to developers.

#### Commas vs Periods

We want the developer to write code once and have it work in all localities. So, the website developer would write `"value": "55.00"` always with periods, but the user agent (e.g. browser) will format this into user locale. For example, US locale will show "55.00", but DE locale will show "55,00".

**Comment by adamroach** [comment]
@pazguille 

> I think use amount in cents is better than decimal because different countries officially designate different symbols for the decimal mark

That would leave us in the odd position of having to decide exactly which currency unit we're using for each currency. The major unit -- dollar for USD, yen for JPY, krona for SEK -- is pretty unambiguous. But minor units become tricky. In your proposal, does SEK use krona or the (functionally deprecated but still legal) öre? Is the number for JPY in yen, sen, or rin?

Even harder: for the currency MRO, would your scheme indicate the price in ouguiya, khoums (1/5th of an ouguiya), or some other scheme, like 1/10th or 1/100th of an ouguiya?

How do we handle transitions that deprecate a minor unit of currency in favor of using its major unit instead? I would think that the potential for being off by factors of 10, 100, or 1000 would be potentially catastrophic for one party or the other in a transaction.

This seems to open up an insanely labyrinthine can of worms for a benefit that hasn't really been explained.

**Comment by dlongley** [comment]
@adamroach,

+1 to everything you said, however:

> This seems to open up an insanely labyrinthine can of worms for a benefit that hasn't really been explained.

I think this may be better stated by indicating there's almost always trade offs in design decisions, and avoiding some potential amount of period/comma confusion in the currency amount by omitting it and adopting minor units results in far worse trouble.

**Comment by adrianhopebailie** [comment]
@pazguille this was discussed at length in the group and the conclusion was to use the format as currently described.
- https://github.com/w3c/browser-payment-api/issues/14
- https://github.com/w3c/webpayments/issues/57
- https://github.com/w3c/webpayments/issues/40
