### ISSUE TITLE
Spec should use [SecureContext] once that is defined in Web IDL

### ISSUE THREAD

**Issue by adrianba** [w3c/browser-payment-api#22]
This issue comes from WICG/paymentrequest#58. Adding [SecureContext] to Web IDL is being tracked in heycam/WEBIDL#65.

**Comment by msporny** [comment]
Migrating https://github.com/w3c/webpayments/issues/20 here:

Should the Browser API be restricted to HTTPS-only environments?

The current consensus seems to be "yes".

@mountielee has asserted that it should be allowed if the user overrides the warning.

**Comment by halindrome** [comment]
I agree that we should use this once it is approved.  However, we should NOT eliminate the prose.  One of the problems with W3C specs that rely upon WebIDL is that there are assumptions in the API definition that are not made explicit in prose.  This leads to implementation errors AND can be confusing for readers who are not WebIDL experts.  The specs need to be Accessible.

**Comment by haavardmolland** [comment]
@msporny, @mountielee: The Browser API should be restricted to secure context only, and I don't believe  we should enable the user to override this (apart from perhaps a low level flag for developers). If a MITM attacker can take control over the merchant site, the payment can be redirected to a different receiver such that the payment ends up at the attacker's account instead of the merchant's, or the attacker can simply trigger a different visa instrument and steal the details.

Browsers have been trying to get rid for security overriding for years. They confuse users and teach them to ignore security warnings (and therefore it would affect security all over, not only for this spec).

**Comment by wseltzer** [comment]
Access to payment information sounds like a canonical case for a hard Secure Context requirement.

**Comment by msporny** [comment]
@msporny wrote:

> The current consensus seems to be "no".

@haavardmolland - Sorry, mistyped that - I meant, the current consensus seems to be "yes". Minor typo. :P

If you read the original issue, you'll see that I was also firmly in the "HTTPS-only" and Secure Context camp. The only "allow override" argument was coming from @mountielee, but I thought it important to point out that there was disagreement that we should discuss.

Security is hard, especially when you turn it off. :)

**Comment by haavardmolland** [comment]
@msporny: Ah, I was struggling to understand how the consensus could be "no" reading the original comments, so that explains it then :).

**Comment by adrianba** [comment]
> However, we should NOT eliminate the prose. 

The prose is likely to be wrong and unnecessary. It looks like the resolution for [SecureContext] will be to make APIs only part of the type system in a secure context.
