### ISSUE TITLE
Normative References

### ISSUE THREAD

**Issue by halindrome** [w3c/browser-payment-api#227]
The spec currently has normative references to two W3C specifications that are not under our control and may not be mature when we want to proceed down the Recommendation track.

[POWERFUL-FEATURES] is a reference to the Secure Contexts spec.  I have no concerns about our requiring secure contexts, but we should not have a normative reference to this spec unless we are certain it will be mature.  An informative reference may be sufficient.

[WEBIDL]  First we are referring to WebIDL level 1... there are features in level 2 that are pretty interesting, but level 2 is far behind on the W3C Rec Track.  In any case, we should be certain we are not using any level 2 features.  Also, we should be using their recommended text about IDL Fragment Definitions as defined in https://www.w3.org/TR/WebIDL-1/#referencing . Finally, we should be sure that WEBIDL is on pace to be at least a PR when we proceed to Rec or we will potentially be delayed waiting for that spec to mature.

**Comment by adrianba** [comment]
I've updated the spec to refer to WebIDL-2, since we are actually using some newer WebIDL capabilities. I'm not too worried about this normative reference - we have been moving API specifications with IDL dependencies to Recommendation for a while despite dependencies on WebIDL-1, which is in the process of transitioning to Proposed Rec. I anticipate that we will need to follow the same processes for WebIDL-2.

The spec already used the language for a conforming user agent (the second part of the #referencing) link. I compared this to other API specifications and this seems sufficient. If you want to add more, please propose specific text.

I updated the [POWERFUL-FEATURES] reference to [SECURE-CONTEXTS] now that SpecRef supports this name. I also changed this to an informative reference since the only mention of "secure context" is in a note (except for the `[SecureContext]` attribute, which is defined in WebIDL.

I hope #259 resolves this issue. If you don't believe so then please reopen and provide concrete text that we can add to close it.
