### ISSUE TITLE
Cannot use 2119 terms in notes

### ISSUE THREAD

**Issue by annevk** [w3c/browser-payment-api#240]
Happens at https://w3c.github.io/browser-payment-api/#dfn-value and maybe elsewhere.

**Comment by halindrome** [comment]
The "should" in that note is not a 2119 term (in that it is not annotated as a 2119 term).  It is just the common English usage of the word.  2119 terms in this and other respec documents are always in uppercase and always annotated with class "2119".  

As an aside, this way of indicating that it is a 2119 term may be insufficient from an accessibility perspective.  I wonder if there shouldn't be a more explicit accessible name so that screen readers have better guidance.  @joanmarie or @marcoscaceres do you have an opinion?

**Comment by annevk** [comment]
It does not have to be annotated for it to be one.

**Comment by marcoscaceres** [comment]
I don't have an opinion re: accessibility, but I do share @annevk's concerns about RFC2119 terms in non-normative text: It can lead to unintentional confusion, particularly because a lot of people (both devs and implementers) end up relying on notes to understand the spec text so they can take the "should" as RFC2119 SHOULD and so on.
