### ISSUE TITLE
The "data" member of  PaymentDetailsModifier doesn't seem to be used for anything

### ISSUE THREAD

**Issue by bzbarsky** [w3c/browser-payment-api#346]
There's no processing model defined for it that I can tell.

**Comment by nickjshearer** [comment]
Isn't it simply intended to be passed back to the payment instrument?

**Comment by ianbjacobs** [comment]
@nickjshearer wrote:

"Isn't it simply intended to be passed back to the payment instrument?"

Yes, except I would say "to the payment app" that handles that payment method. The payment app could be the browser or a third party payment app.

Ian

**Comment by bzbarsky** [comment]
You can't pass an object to a third-party payment app.  See also https://github.com/w3c/browser-payment-api/issues/307

**Comment by rsolomakhin** [comment]
We can run `JSON.stringify(data)` and pass the result to the third-party payment app.

**Comment by bzbarsky** [comment]
OK, that's fine.  The spec then needs to:

1. Define exactly when JSON.stringify runs, because it can have observably side-effects.  Again, see https://github.com/w3c/browser-payment-api/issues/307

2. Define that the resulting string is passed somewhere, wherever that is.

**Comment by domenic** [comment]
Can someone (@rsolomakhin?) help me understand exactly in which steps the data is passed to the payment app? For example, we determined that the methodData (parsed into [[parsedMethodData]]) is passed to the payment app in canMakePayment and in show. Is the idea that the payment apps should receive not only the method data, but also the payment details modifier data, at both of those points?

**Comment by rsolomakhin** [comment]
Both `.canMakePayment()` and `.show()` should be sending the method-specific `data` to the payment app, because that can include some important filtering information. For example, `data` for `"basic-card"` payment method includes `supportedNetworks`. If merchant specifies `supportedNetworks: ["jcb"]`, but the only installed payment app is not aware of JCB, then `.canMakePayment()` should resolve with `false` and `.show()` should reject with `NotSupportedError`.

As for modifiers, that should be used for altering the price, which is important when completing a transaction, not when determining whether a transaction can procede. Therefore, modifiers should be sent to the payment app with `.show()`, but not in `.canMakePayment()`.
