### ISSUE TITLE
waitForUpdate is not defined

### ISSUE THREAD

**Issue by domenic** [w3c/browser-payment-api#371]
I can't tell who is supposed to hold this. Is it one per document? One per PaymentRequest?

**Comment by domenic** [comment]
This still remains mysterious. @adrianba @rsolomakhin any ideas what [[waitForUpdate]] is about?

**Comment by dlongley** [comment]
@domenic,

`[[waitForUpdate]]` is an internal slot in `PaymentRequestUpdateEvent`. I believe it gets flipped when someone calls `updateWith` from within an event handler so that:

1. An invalid state exception will be thrown if `updateWith` is called more than once.
2. As a guard that will prevent event handling from completing until unset again.

https://github.com/domenic/browser-payment-api/blob/85074dda44c64c088f87f961ac503783dc22114b/index.html#L1623-L1624

I believe its analog is the "[wait to respond flag](https://www.w3.org/TR/service-workers/#wait-to-respond-flag)" used in the fetch spec's [respondWith method](https://www.w3.org/TR/service-workers/#fetch-event-respondwith-method).

Does that answer your question?

**Comment by domenic** [comment]
Yes, that's very helpful; thank you!
