### ISSUE TITLE
Editorial: don't capitalize RFC 2119 terms

### ISSUE THREAD

**Issue by domenic** [w3c/browser-payment-api#377]
It's really distracting

**Comment by marcoscaceres** [comment]
Should fix this in ReSpec... at least make it a flag ⛳️

**Comment by domenic** [comment]
The source text also contains a lot of capitalized MUSTs that would probably have to go away. Or maybe you were thinking of ReSpec de-capitalizing?

**Comment by marcoscaceres** [comment]
> ReSpec de-capitalizing

ReSpec marks them up, so I can CSS `text-transform` them. The key thing is to keep them marked up, but we can style them however we want. However, we do want them in the source capitalized, because it's proved useful in the past to extract conformance requirements for testing and conformance-checking purposes.

**Comment by marcoscaceres** [comment]
Fixed in ReSpec. Kept RFC2119 keywords red(ish) tho... incremental improvements and all that... can progressively turn them to black over the next year ;)
