### ISSUE TITLE
Serializer behavior

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#385]
Should `PaymentResponse` serializer return null, empty, or undefined `payerName` when `requestPayerName` was `false` in options?

**Comment by marcoscaceres** [comment]
You need to check what WebIDL says about serialization of nullable attributes (as it pertains to the PaymentResponse). The serialized behaviour wont be tied to the request dictionary. 

Im currently on my phone, so hard to look up. Hopefully the above helps. Let's us know tho, as I'm also interested to know what it will be 🙂

**Comment by rsolomakhin** [comment]
My reading of the WebIDL spec points to "Use `null`" answer, but please double-check me.

**Comment by domenic** [comment]
I think the problem here is that the "user accepts the payment request algorithm" doesn't set any value at all for payerName if requestPayerName is not true. It should set it to null, probably. Or it could set it to the empty string. (undefined is not allowed by the DOMString? typing.) Right now it's not defined what it's set to.

Once that's done, Web IDL will take care of serializing things to whatever you set it to.

**Comment by marcoscaceres** [comment]
I'm going to set it to null, if you don't get anything back. The user may also opt to not provide this information, even if the site requests it.
