### ISSUE TITLE
canMakePayment() might be in the wrong place?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#403]
If it's not too late, I'm wondering if we can move `canMakePayment()` to be a static on the `PaymentRequest` interface? The idea would be that a site can query payment methods like so:

```JS
const result = await PaymentRequest.canMakePayment(...ids);
```

It means that we don't need to spin up a `PaymentRequest` instance to do the check.

**Comment by marcoscaceres** [comment]
I mean "canMakePayment"... fixing above...

**Comment by rsolomakhin** [comment]
I would prefer that we keep that API as-is. I view spinning up an instance of `PaymentRequest` as an advantage, not a detriment, because this warmed up instance of `PaymentRequest` will be able to respond to `.show()` call much faster, now that it has queried the installed payment apps.

By the way, Chrome [has shipped](https://www.chromestatus.com/feature/5702608073261056) `.canMakePayment()` in M56, which is currently in beta, soon to be stable.

**Comment by marcoscaceres** [comment]
Ok, np. Wanted to check as I wasn't sure about it shipping.

**Comment by domenic** [comment]
Also the algorithm requires passing along the parsed method data; see step 6.

**Comment by Edouard-chin** [comment]
Hello guys,

Sorry to dig up this issue and apologize in advance if this is the wrong place to ask; 
I'm questioning the value of `canMakePayment`  method on an instance of PaymentRequest in a real world situation.
All code examples of `canMakePayment` assumes that we have the checkout data (total amount, currency …) as soon as the page loads.
In most cases I believe this can't be realistic and we would have to wait for an action from the user (i.e click on a checkout button) in order to spin up an instance of paymentRequest.

If one wanted to determine whether a user can make payment before having the checkout data, that would mean he would have to create a first instance of PaymentRequest with dummy data; and then   recreate an other instance when the user clicks on the checkout button.

```js
// Page loads, one has to determine if user can make payment
const data = {displayItems: [], total: {label: '', amount: {currency: 'USD', value: '1.00'}}}; // dummy data
const request = new window.PaymentRequest(instruments, data);
request.canMakePayment().then((result) => {
  // Perform some logic (display an extra button, hijack the regular checkout button ...)
})


// User clicks on the checkout button, request goes to the backend to create a checkout and retrieve the real data
const request = new window.PaymentRequest(instruments);
request.show().then(() => …)

**Comment by rsolomakhin** [comment]
I believe the idea is to create a new `PaymentRequest` object for every new state of the checkout shopping cart. So your code would become:

```javascript
// User has added an item to the shopping cart.
function onShoppingCartContentsUpdated(data) {
  request = new window.PaymentRequest(instruments, data);
  request.canMakePayment().then((result) => {
    // Perform some logic.
  }
}

// User clicks on the checkout button
function onCheckoutButtonClicked() {
  request.show().then((instrumentResponse) => {});
}
```

**Comment by Edouard-chin** [comment]
Thanks for your answer Rouslan.

The usual and classic flow on any e-commerce stores is as follow:
1. Customer add products to cart
2. Customer clicks on the "Checkout button", which redirects to some "summary page" 
3. Customer is ready and click on another "Checkout button" which redirects this time to the traditional checkout forms

If one wanted to perform some `canMakePayment` logic while on step 3, he would have to spin-up 2 instances of paymentRequest.

Your example is great and I get the idea, but this would assume the customer will get the paymentRequest slate on the first checkout button click (step 2 above), and won't have time to see the summary of his cart.

Of course we can add this summary directly into the paymentRequest slate (lineItems), but I'm wondering if this is the best for the customer in term of UI (more than 5 items and the Payment slate becomes hard to read)

**Comment by rsolomakhin** [comment]
Perhaps it would be better to initialize the `PaymentRequest` instance when the customer lands on the "summary page" in step 2. Then, when the customer is ready to click on another "Checkout button" in step 3, you can call `request.show()` instead of redirecting to the traditional checkout form. (If `PaymentRequest` is not supported, you can fall back to the traditional checkout forms.) Would that work?

**Comment by Edouard-chin** [comment]
I feel like my question needs more context although I'm still asking myself if this problem is specific to our platform or more generally the `canMakePayment` design, apologize again if it's the former.

At Shopify, we have the concept of `Cart` and `Checkout`. A `Checkout` gets created when the customer is done reviewing his cart (he his on the summary page and finally clicks on checkout which redirects him to the classic form).
A `Cart` doesn't have a notion of currency or even taxes, one of the reason we need to wait for the checkout to be created to instantiate PaymentRequest.

If you navigate to https://paymentrequest.myshopify.com/cart (add product first to your cart), and click on checkout, you should see the PaymentRequest slate opening. The PaymentRequest object gets instantiated right when you click on the "Checkout" button (we make couple requests first to create the checkout, and retrieve back the data).
We also can't create the checkout when the user lands on the summary page as it would be a waste of resources if the user finally decide to **not** checkout.

Let's say we wanted to perform some `canMakePayment` logic even before the customer clicks on the checkout button, because the checkout is not yet created, we would have no other choice but to instantiate a PaymentRequest instance with dummy data.

I believe this notion of Cart and Checkout is not specific to Shopify but most e-commerce platform.

**Comment by rsolomakhin** [comment]
I'm not opposed to instantiating `PaymentRequest` with dummy data to find out whether `.canMakePayment()` will return `true`.

```javascript
// The page has loaded. Should the page use PaymentRequest?
// If PaymentRequest fails, should the page fallback to manual
// web form checkout?
const supportedPaymentMethods = ...
let shouldCallPaymentRequest = true;
let fallbackToLegacyOnPaymentRequestFailure = false;
(new PaymentRequest(supportedPaymentMethods,
    {total: {label: 'Stub', amount: {currency: 'USD', value: '0.01'}}})
.canMakePayment()
.then(function(result) {
  shouldCallPaymentRequest = result;
}).catch(function(error) {
  console.log(error);
  // The user may have turned off query ability in their privacy settings.
  // Let's use PaymentRequest by default and fallback to legacy
  // web form based checkout.
  shouldCallPaymentRequest = true;
  fallbackToLegacyOnPaymentRequestFailure = true;
});

// User has clicked on the checkout button. We know
// what's in the cart, but we don't have a `Checkout` object.
function onCheckoutButtonClicked(lineItems) {
  callServerToRetrieveCheckoutDetails(lineItems);
}

// The server has constructed the `Checkout` object. Now we know
// all of the prices and shipping options.
function onServerCheckoutDetailsRetrieved(checkoutObject) {
  if (shouldCallPaymentRequest) {
    const request = new PaymentRequest(supportedPaymentMethods, checkoutObject);
    request.show().then(function(paymentResponse) {
      // Post the results to the server and call `paymeResponse.complete()`.
    }).catch(function(error) {
      console.log(error);
      if (fallbackToLegacyOnPaymentRequestFailure) {
        window.location.href = '/legacy-web-form-checkout';
      } else {
        showCheckoutErrorToUser();
      }
    });
  } else {
    window.location.href = '/legacy-web-form-checkout';
  }
}
```

If you call `.canMakePayment()` multiple times, keep in mind that the first parameter to the `PaymentRequest` constructor should contain the same data

**Comment by Edouard-chin** [comment]
> I'm not opposed to instantiating PaymentRequest

Sounds great. Thanks a lot for your feedbacks and quick answers. ❤️
