### ISSUE TITLE
Is 'currencySystem' required?

### ISSUE THREAD

**Issue by rsolomakhin** [w3c/browser-payment-api#408]
[The spec says](https://w3c.github.io/browser-payment-api/#paymentcurrencyamount-dictionary):

> The following fields are required:
> `currencySystem`...

However, the WebIDL for `currencySystem` does not have the `required` keyword. Let's change the phrasing of the spec to make it clear that `currencySystem` is optional. The developer could, for example, not specify it, or specify `currencySystem: null` or `currencySystem: undefined`, correct?

**Comment by tommythorsen** [comment]
I vote for just erasing the string `The following fields are required:` from [Section 5](https://w3c.github.io/browser-payment-api/#paymentcurrencyamount-dictionary) of the specification. While we're at it, I would erase such strings from [Section 10](https://w3c.github.io/browser-payment-api/#paymentitem-dictionary) and [Section 12](https://w3c.github.io/browser-payment-api/#paymentshippingoption-dictionary) as well.

**Comment by ianbjacobs** [comment]
As long as the WebIDL is normative, that seems fine. The section on conformance seems to confirm this:
 "As well as sections marked as non-normative, all authoring guidelines, diagrams, examples, and notes in this specification are non-normative. Everything else in this specification is normative. "

Ian

**Comment by romandev** [comment]
It might be correct. Because it's not nullable and it has default value. So, the value is always set as something. So, we can say the value is always required. (But we can change the string clearer.)

Also, according to IDL spec[1], the currency system (non-nullable DOMString) will be resolved as follows:
currencySystem: null -> "null"
currencySystem: undefined -> "urn:iso:std:iso:4217" (default value)

[1] https://heycam.github.io/webidl/#idl-DOMString

**Comment by marcoscaceres** [comment]
I agree with @tommythorsen - we should not replicate what is in the IDL.
