### ISSUE TITLE
should .show() be user gated?

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/browser-payment-api#486]
Followup from #462. 

If the browser crashes and restarts by reopening N number of tabs. A tab in the background calls `.show()` and it now blocks all payment requests (at least, for a time - assuming it does not focus the tab, which is also not in the spec).

To protect from the above, should we then make it that `.show()` is gated on user interaction?

**Comment by mnoorenberghe** [comment]
This would also help to prevent:
1) annoying drive-by requests like we see with alert/confirm spamming and 
2) clickjacking attacks if a UA allows a one-click purchase (of course delays on the button are another way to mitigate the latter).

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

What does "gated by" mean exactly? If one goal is to minimize user interaction to make a payment, what is the impact of gating?

Thanks!

Ian

**Comment by rsolomakhin** [comment]
Requiring a user gesture for `.show()` is OK with me. @zkoch Thoughts?

**Comment by dlongley** [comment]
This seems like a good idea to me. However, would this be a problem for scenarios where users only interact on origin A -- which uses `postMessage` to trigger origin B (in an iframe) to call the API? Are there existing payment systems that look like this or that may want to function this way if adopting the payment request API?

@ianbjacobs,

> What does "gated by" mean exactly?

I think it means that the `.show()` API can only be invoked when handling some kind of user-triggered event (e.g. the user clicked on something).

> If one goal is to minimize user interaction to make a payment, what is the impact of gating?

I think it was (probably) always assumed that we want the user to do something to trigger showing the payment UI vs. it coming up without them doing anything on a website. The only question in my mind is whether or not there are scenarios where a user may have been redirected to a payment site (or one loads in an iframe) via a "buy" button and it would then be cumbersome to require an additional gesture once they land there.

**Comment by mattsaxon** [comment]
This would appear to limit the possibility of invisible payments, for example if the user has given prior consent for payments to a certain merchant within a certain threshold.

I think it should be a MAY require a jesture, but MUST if prior consent has not been obtained.

**Comment by nickjshearer** [comment]
> However, would this be a problem for scenarios where users only interact on origin A -- which uses postMessage to trigger origin B (in an iframe) to call the API? Are there existing payment systems that look like this or that may want to function this way if adopting the payment request API?

User agents can propagate the user gesture across the postMessage boundary. WebKit does this today, for example.

I would expect some implementors to want to make `show()` conditional on a user gesture, so that definitely shouldn't be prohibited by the spec. I don't know if it needs to be required.

**Comment by zkoch** [comment]
I'm torn on this point. I'm generally skeptical of how effective "user gesture" is at a mitigating factor given that a 'click' or 'tap' anywhere is a user gesture. There are also legitimate uses cases we've seen where you wouldn't want this. For example, a merchant wants to implement PaymentRequest, and the shortest path to doing so is just to invoice PR.show() on the redirect to /checkout. It's completely in line with user expectations and is easy to implement.

If we decide to say something about this in the spec, I think it needs to be in the form of 'MUST' language. Since this would impact an implementation decision, such as in the use case above, users have to be able to reason about whether their implementation would work cross-browser.

**Comment by marcoscaceres** [comment]
@dlongley wrote: 
> This seems like a good idea to me. However, would this be a problem for scenarios where users only interact on origin A -- which uses postMessage to trigger origin B (in an iframe) to call the API? Are there existing payment systems that look like this or that may want to function this way if adopting the payment request API?

That would not work in this scenario, as that's akin to click jacking. 

@zkoch wrote: 
> If we decide to say something about this in the spec, I think it needs to be in the form of 'MUST' language. Since this would impact an implementation decision, such as in the use case above, users have to be able to reason about whether their implementation would work cross-browser.

Yes, it would need to be a MUST and would throw without the click.

We could go without it initially and see how people use the API... if it becomes a problem, we can add it later.

**Comment by mnoorenberghe** [comment]
> We could go without it initially and see how people use the API... if it becomes a problem, we can add it later.

I think we should do the opposite since it's way harder to add the restriction later compared to removing it. I don't think we should be adding new features to the web platform that can be used to annoy users outside the content area just by simply visiting a page. 

> There are also legitimate uses cases we've seen where you wouldn't want this. For example, a merchant wants to implement PaymentRequest, and the shortest path to doing so is just to invoice PR.show() on the redirect to /checkout. It's completely in line with user expectations and is easy to implement.

I agree that such an implementation would be in line with user expectations but I still would rather not keep open the door for malicious authors. Legitimate sites can take a longer path to work with the API so that the web doesn't have a new annoyance API to support forever.

**Comment by marcoscaceres** [comment]
We (Mozilla) have discussed this a bit more internally, and we still feel we should have some minimal protection for `show()`. We concur that getting the user to "click" somewhere sets a fairly low bar. However, similar to pop-up blocking, just because we know it's not perfect doesn't mean we shouldn't try to prevent abuse. 

Would love to hear opinions from @nickjshearer (if Apple Pay is user gated in some way) and the folks at Microsoft.

**Comment by rvm4** [comment]
Marcos, Zach and I spoke and we came to the counter-proposal that the .show() API will only render things if the tab has focus. We could not think of a valid use case for rendering the .show() UI without there being focus. So the proposal is to throw some sort of security exception if a tab/page without focus were to invoke .show().

**Comment by marcoscaceres** [comment]
For clarity... 

```JS
if (!window.top.document.hasFocus()){
  throw new DOMException("Top window must be focused to call .show()", "SecurityError");
}
```

@domenic, wdyt?

**Comment by dlongley** [comment]
@marcoscaceres,

I don't think that code example is exactly right as active elements may not have focus. I'm also not sure that it would be correct for (cross-origin) iframes that call `show()`, but perhaps it's correct in spirit. :)

(Note: even executing `window.top.document.hasFocus` as I'm typing this right now returns `false` yet I'm clearly viewing the tab I'm typing into. EDIT: I found this strange so I put it on a `setInterval` and I did get `true` ... switching to the console to execute the JS made it lose focus :).)

**Comment by marcoscaceres** [comment]
> On 6 Apr 2017, at 11:08 pm, Dave Longley <notifications@github.com> wrote:
> 
> @marcoscaceres,
> 
> I don't think that code example is exactly right as active elements may not have focus.
> 

What's an "active element"?

> I'm also not sure that it would be correct for iframes that call show(), but perhaps it's correct in spirit. :)
> 

That's why we have an attribute on iframes to explicitly allow this. 

> (Note: even executing window.top.document.hasFocus as I'm typing this right now returns false yet I'm clearly viewing the tab I'm typing into.)
> 
Your dev tools have focus ^_^ try it with setTimeout and actually focusing the document by clicking on it.

**Comment by dlongley** [comment]
@marcoscaceres,

> What's an "active element"?

I took that from the [Mozilla dev docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/hasFocus) on `Document.hasFocus`:

> When viewing a document, an element with focus is always the active element in the document, but an active element does not necessarily have focus. For example, an active element within a popup window that is not the foreground does not have focus.
> 
> Return Value
> 
> false if the active element in the document has no focus; true if the active element in the document has focus.

> That's why we have an attribute on iframes to explicitly allow this.

You missed my edit in there since you replied via email -- I added `(cross-domain)` as a qualifier for the iframe; I don't think you can access the `document` property of `window.top` in that case to even check the focus. If you *could*, which the native browser code presumably can, then I would expect this to work -- which is why I said it seemed correct in spirit :).

> Your dev tools have focus ^_^ try it with setTimeout and actually focusing the document by clicking on it.

Yeah, I had an edit after my original reply where I noticed the same thing and used `setInterval` to test.

**Comment by nickjshearer** [comment]
@marcoscaceres 
> Would love to hear opinions from @nickjshearer (if Apple Pay is user gated in some way)

Sorry, I should have been clearer - when I said:

> User agents can propagate the user gesture across the postMessage boundary. WebKit does this today, for example.

...that applies to Apple Pay. Invocation must be handled off a user gesture. I would agree that something is better than nothing.

**Comment by zkoch** [comment]
In chatting with a few other folks on Chrome and what we've learned from *not* have things gated on user actions (e.g. a series of redirects from an ad, all of which can call PR), it seems like we might need to have something here. This is me flip flopping.

**Comment by adrianba** [comment]
This issue was opened related to crash recovery. I think implementations should take whatever measures they think appropriate when dealing with crash recovery.

The discussion here has instead focused on whether a user gesture is needed to protect the user from either something annoying (showing the dialog when the user doesn't expect it) or something worse (which I'm not clear on).

I think the spec should allow implementations to provide a variety of mitigations here and we should be clear what happens if the payment request is rejected (e.g. what exception to throw). I'm not entirely convinced that we need to specify a user gesture or focus check as a requirement though.

**Comment by adrianba** [comment]
The spec already says:

> Implementations __may also require a user action to initiate a payment request__ or they may choose to rate limit the calls to the API to prevent too many repeated calls. 

This allows but does not require the user gesture. I think this is sufficient.

**Comment by adrianba** [comment]
Discussed on the editor's call - working on a PR.
