### ISSUE TITLE
'Pull' Payment Bias in API spec

### ISSUE THREAD

**Issue by mattsaxon** [w3c/browser-payment-api#499]
[Section 16.3](https://www.w3.org/TR/payment-request/#details-attribute) states "... by the merchant to process the transaction and determine successful fund transfer"

Suggest "... by the merchant to process the transaction and/or determine successful fund transfer"

**Comment by ianbjacobs** [comment]
In light of my other editorial counter-proposal [1] (and because I prefer to avoid an "and/or" construct), how about:

 "by the merchant to process or validate a transaction (depending on the <a>payment method</a>)."

Also, if we move in the direction of "payee"  here, that would become:

 "by the payee to process or validate a transaction (depending on the <a>payment method</a>)."

Ian

[1] https://github.com/w3c/browser-payment-api/pull/474#discussion_r109010151

**Comment by mattsaxon** [comment]
+1

**Comment by marcoscaceres** [comment]
Closed via https://github.com/w3c/payment-request/pull/599, I believe.

**Comment by ianbjacobs** [comment]
(I hope so, too!)
