### ISSUE TITLE
Drop array support for supported methods?

### ISSUE THREAD

**Issue by zkoch** [w3c/browser-payment-api#549]
Given what's happening in https://github.com/w3c/browser-payment-api/pull/536, should we consider just dropping support for an array of supportedMethods? And just move to a simple string?

It simplifies the story quite a bit, and the original idea for making it an array was so we could do "supportedMethods: ['visa', 'mc']"?

@domenic was mentioning technically this might not be that bad given how the webidl works...

**Comment by ianbjacobs** [comment]
Hi @zkoch, 

I think that makes sense for two reasons:

 * Payment method specific data is not likely to be shared.
 * Even in some edge case where it were sharable, you would only suffer some inconvenience,
    not loss of functionality. 

Thanks for recalling the original reason for the list: this was conceived before we moved individual card networks from N payment methods to basic card.

Do you consider moving from an array to a string a substantive change for implementations?

Ian

**Comment by domenic** [comment]
> @domenic was mentioning technically this might not be that bad given how the webidl works...

To expand: if we change the type to DOMString,

- `supportedMethods: ["foo"]` will be treated by implementations as `supportedMethods: "foo"`, which does not break anyone's apps.
- `supportedMethods: ["foo", "bar"]` will be treated by implementations as `supportedMethods: "foo,bar"`, which will break things.

(This is because converting to DOMString via Web IDL is basically the same as calling `x.toString()`, and `toString()` for arrays behaves like the above.)

So it only breaks when people are already using multiple supported methods (with the same data), which seems less likely today.

**Comment by marcoscaceres** [comment]
Agree this would simplify things quite a lot. The problem is that "methods" implies a list, but could live with that for the sake of compat with what's already shipped. I guess we need an ok from @adrianba and friends before we can make this change.

**Comment by dlongley** [comment]
Could always add a `supportedMethod` and require just one of them to be present for a time for backwards compatibility.

**Comment by marcoscaceres** [comment]
No, that would be confusing for everyone. Once things get put in the wild on the web, it's nearly impossible to deprecate them (people start copy pasting, articles get written, etc.). 

We just need an ok from Microsoft here to make the change to limit the damage early and quickly.

**Comment by dlongley** [comment]
I respectfully disagree on two counts. The first is perhaps a nit -- it is not nearly impossible to *deprecate* things, it just may be nearly impossible to actually remove them. Plenty of other Web technology has been deprecated or changed after being in the wild. Secondly, I don't think this particular stuff is so "in the wild" yet that it's an unstoppable force. I do understand the potential technical debt that arises when things are rushed out the door -- and many of us in the WG argued this point earlier on a number of issues.

That being said, I also don't think this particular naming issue matters that much either way. Hopefully the biggest take away is that if we feel the need to expose this stuff to the wild early, we should always prefer singular names for properties because it's more natural (IMO) to allow something to become plural (by means of an array) than to go in the other direction. This lesson has been learned in a number of other communities and we should follow suit.

**Comment by ianbjacobs** [comment]
Hi all,

The name "supportedMethods" is now confusing since the value is a single payment method identifier. 

I propose the addition of an informative note, something like:

  supportedMethods: [current definition here] Note: The value of this member changed
  from an array to a string, but the (plural) name "supportedMethods" was maintained
  for reasons of compatibility.

Ian

**Comment by marcoscaceres** [comment]
The note sounds good. Please send a PR.

**Comment by ianbjacobs** [comment]
I included the note(s) in this PR:
 https://github.com/w3c/browser-payment-api/pull/559

Ian

**Comment by RByers** [comment]
I don't see any chromium bug filed to track updating it's implementation for this spec change.  Filed [this one](https://bugs.chromium.org/p/chromium/issues/detail?id=754779).

**Comment by marcoscaceres** [comment]
Thanks @RByers for filing it. Chrome is failing all WPT related to payment because of this - so will be great to see Chrome's results go back to being all green 💚

**Comment by RByers** [comment]
Yeah @marcoscaceres, the failing WPT is exactly how I noticed this :-)
