### ISSUE TITLE
Don't understand how to support outsourced payment providers using CNP + basic card

### ISSUE THREAD

**Issue by cyberphone** [w3c/browser-payment-api#566]
I have probably misunderstood the API but right now I have a setup with an outsourced payment provider who deals with CNP (Card Not Present) payments which I'm trying to rewrite for the PaymentRequest API.

I'm stuck converting this to setup to use "basic card" unless I offload the entire PaymentRequest handling to the outsourced payment provider which I don't want since there is a PayPal provider as well (which I BTW don't understand how to support either).

Using "basic card" on the Merchant side wouldn't work either since then the Merchant would see card data which was the reason for using an external payment service in the first place.

**Comment by ianbjacobs** [comment]
@cyberphone,

There is a task force of the Working Group discussing tokenized card payments. I suspect that a future payment method for tokenized card payments would address your need, namely of shielding the merchant from card data. Please stay tuned for more information about tokenized card payments.

Because this question does not bear directly on Payment Request API, I am going to close this issue. 

Ian
