### ISSUE TITLE
What about billet payment option?

### ISSUE THREAD

**Issue by mauricionr** [w3c/browser-payment-api#577]
Here in brazil we pay a lot of things on the internet with billet?

Any discussion if this payment method should be supported in the payment request?

in my opinion this payment option could make the adoption of the payment request API get bigger in brazil.

Thanks :smile:

**Comment by ianbjacobs** [comment]
Hi @mauricionr,

We discussed Boleto payments a couple of years ago:
 https://www.w3.org/2015/06/18-wpay-minutes#usecases

We have not talked lately about a Boleto payment method specification. I am going to close the issue here and instead have pinged our CIP friends on his topic:
 https://lists.w3.org/Archives/Public/public-payments-wg/2017Aug/0005.html

Thanks!

Ian
