### ISSUE TITLE
Add support for crypto currencies 

### ISSUE THREAD

**Issue by ghost** [w3c/browser-payment-api#627]

**Comment by ianbjacobs** [comment]
Hi @AhsanE,

Thanks for reaching out and suggesting that the Working Group look into cryptocurrency payment methods. I would reframe your issue as follows:

1) Payment Request API is designed to accommodate different payment methods. We capture the data and flow requirements for these in "payment method specifications." I hear part of your comment as "there should be cryptocurrency payment method specifications." If that is one thing you have in mind, then we would need Working Group participants to develop these and propose to the Working Group, which would make a decision whether to take up the work.

2) Payment Request API needs feature changes in order to be useful with a wide variety of payment methods, including cryptocurrency payment methods. I think we may not know what these issues are until we have some experience with cryptocurrency payment methods. 

Because this issues list is for issues specific to the Payment Request API, I am going to close this issue and move your proposal to our general issues list:
 https://github.com/w3c/webpayments/issues/232

Ian

**Comment by giorgionetg** [comment]
Currently Interledger Protocol, that is also a candidate method payment is based on cryptocurrencies... We need to wait w3c decision and regulators I guess...
There are allready example like XRPtipbot and Coil that works with ILP...
