### ISSUE TITLE
window.PaymentRequest returns undefined randomly

### ISSUE THREAD

**Issue by semcelik** [w3c/browser-payment-api#967]
Hello, 
I have implemented PaymentRequest api to receive payments via Apple Pay on safari browsers. I have realised that sometimes `window.PaymentRequest` returns undefined randomly. It is very hard to reproduce it randomly happens.  When i try to reproduce that on same browser (in different incognito windows) it returns correctly. Is there any reason for that? Or how can i fixed that issue? You can see the sample screenshots below.

Notes: 
- Both screenshots has been taken from **Safari Version 14.0.3 (16610.4.3.1.7)**
- It happens in different Safari versions too
- I dont have any extension in that browser

**SUCCESSFUL CASE**
![image](https://user-images.githubusercontent.com/25296714/135441857-202be8f6-3be0-414d-ae1e-63c3eabb843f.png)

**UNDEFINED CASE**
![image](https://user-images.githubusercontent.com/25296714/135441944-03cfec39-3bdf-4bb1-a2cd-8cd5b16fee7a.png)

**Comment by stephenmcgruer** [comment]
If I understand correctly, this is actually a bug report against an implementation of PaymentRequest, in Safari, and as such the appropriate place to file a bug would be https://bugs.webkit.org/ rather than the spec repository. As such, I'm going to close this issue.

That said, my immediate suspicion would be that PaymentRequest is HTTPS-only, and perhaps you're testing on a devtools connected to a HTTP site when it returns undefined? (e.g. compare trying it on https://google.com and http://example.org).
